---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "radarr.fullname" . }}-api-key
  labels:
    {{- include "radarr.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ randAlphaNum 32 | b64enc | quote }}