{{- $name := printf "%s-config" (include "radarr.name" .) -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $name }}-pvc
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 1Gi
