---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "radarr.fullname" . }}
  labels:
    {{- include "radarr.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "radarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "radarr.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "radarr.serviceAccountName" . }}
      securityContext:
        fsGroup: 100
      initContainers:
        - name: volume-permissions
          image: busybox:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              chown -R 99:100 /config && chmod -R 755 /config
          volumeMounts:
            - name: config
              mountPath: /config
        - name: {{ .Chart.Name }}-init
          image: busybox:latest
          command: 
            - "/bin/sh"
            - "-c"
            - |
              cat /tmp/config/config.xml.template | \
              sed "s/\${POSTGRES_HOST}/$POSTGRES_HOST/g" | \
              sed "s/\${POSTGRES_PORT}/$POSTGRES_PORT/g" | \
              sed "s/\${POSTGRES_USER}/$POSTGRES_USER/g" | \
              sed "s/\${POSTGRES_PASSWORD}/$POSTGRES_PASSWORD/g" | \
              sed "s/\${API_KEY}/$API_KEY/g" > /config/config.xml && \
              chmod 644 /config/config.xml
          env:
            - name: POSTGRES_HOST
              value: "{{ include "radarr.fullname" . }}-rw"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "radarr.fullname" . }}-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "radarr.fullname" . }}-db-credentials
                  key: password
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "radarr.fullname" . }}-api-key
                  key: api-key
          volumeMounts:
            - name: config-init
              mountPath: /tmp/config
            - name: config
              mountPath: /config
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PUID
              value: "99"
            - name: PGID
              value: "100"
            - name: UMASK
              value: "022"
            - name: TZ
              value: America/New_York
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: media
              mountPath: /media
            - name: config
              mountPath: /config
            - name: backups
              mountPath: /backups
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: {{ include "radarr.name" . }}-media-pvc
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "radarr.name" . }}-config-pvc
        - name: backups
          persistentVolumeClaim:
            claimName: {{ include "radarr.name" . }}-backups-pvc
        - name: config-init
          configMap:
            name: {{ include "radarr.fullname" . }}
