{{- if .Values.ingress.enabled }}
{{- $domain_name := include "common.domain_name"  (dict
  "domain" .Values.ingress.domain
  "name" (include "radarr.name" .)
)}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "radarr.fullname" . }}
  labels:
    {{- include "radarr.labels" . | nindent 4 }}
  annotations:
    # Cloudflare External DNS hostname annotation
    external-dns.alpha.kubernetes.io/hostname: {{ $domain_name }}
    external-dns.alpha.kubernetes.io/target: {{ printf "%s.cfargotunnel.com" .Values.cloudflare.tunnelId }}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"

    # Apply user-defined annotations from values
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

    {{- if .Values.ingress.performance.enableOptimizations }}
    # Performance optimizations
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "{{ .Values.ingress.performance.timeouts.connect }}"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "{{ .Values.ingress.performance.timeouts.send }}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{ .Values.ingress.performance.timeouts.read }}"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
  - hosts:
    - {{ $domain_name }}
    secretName: {{ include "radarr.fullname" . }}-tls
  rules:
  - host: {{ $domain_name }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "radarr.fullname" . }}
            port:
              number: 80
{{- end }}
