---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "radarr.fullname" . }}-db-credentials
  labels:
    {{- include "radarr.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  username: radarr
  password: {{ randAlphaNum 16 | quote }}
  radarr-user: radarr
  radarr-password: {{ randAlphaNum 16 | quote }}
