---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "radarr.fullname" . }}
  labels:
    {{- include "radarr.labels" . | nindent 4 }}
  annotations:
    cnpg.io/forceBinaryUpgrade: "true"
    argocd.argoproj.io/sync-wave: "-1"
spec:
  instances: 1
  postgresql:
    parameters:
      shared_buffers: "256MB"
      # Standard PostgreSQL parameters for data safety
      synchronous_commit: "on"
      full_page_writes: "on"
      fsync: "on"
      # Performance and security parameters
      max_connections: "100"
      work_mem: "4MB"
      log_min_duration_statement: "1000"  # Log queries taking more than 1 second
      password_encryption: "scram-sha-256"
  storage:
    storageClass: postgres
    size: 2Gi
  bootstrap:
    # Added bootstrap configuration
    initdb:
      database: radarr-main
      owner: radarr
      secret:
        name: {{ include "radarr.fullname" . }}-db-credentials
      postInitSQL:
        - CREATE DATABASE "radarr-log" WITH OWNER "radarr";
  serviceAccountTemplate:
    metadata: {}
  monitoring:
    enablePodMonitor: true
  enableSuperuserAccess: true
