---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - base/argo-cd-issuer.yaml
  - base/argo-cd-certificate.yaml
  - base/argo-cd-ui-ingress.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/refs/tags/v2.14.6/manifests/ha/install.yaml
patches:
  - path: overlays/argo-cd-cm.yaml
