apiVersion: v2
name: profilarr
description: A Helm chart for Profilarr - Configuration management tool for Radarr/Sonarr
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: common
    version: "*"
    repository: "file://../common"