---
resources: {}
nfsServer: 0.0.0.0
ingress:
  enabled: false
  domain: ''
  className: nginx
  tls: true
  annotations: {}
service:
  type: LoadBalancer
  port: 6868
serviceAccount:
  create: true
  automount: true
  annotations: {}
replicaCount: 1
image:
  repository: santiagosayshey/profilarr
  pullPolicy: IfNotPresent
  tag: latest
timezone: America/New_York
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
