resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi
nfsServer: 0.0.0.0
cloudflare:
  enabled: false
  tunnelId: ''
ingress:
  enabled: true
  domain: ''
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: acme-prod
    external-dns.alpha.kubernetes.io/ttl: '120'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: '0'
  security:
    enableSecurityHeaders: true
  performance:
    enableOptimizations: true
    timeouts:
      connect: 300
      send: 300
      read: 300
service:
  type: LoadBalancer
  port: 8989
serviceAccount:
  create: true
  automount: true
  annotations: {}
image:
  repository: lscr.io/linuxserver/sonarr
  pullPolicy: IfNotPresent
  tag: 4.0.14.2939-ls283
postgres:
  storageClass: longhorn
profilarr:
  enabled: true
  url: http://profilarr.media.svc.cluster.local
  apiKeySecret: profilarr-api-key
  apiKeySecretKey: api-key
