resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi
media:
  nfsServer: 0.0.0.0
  nfsPath: ''
cloudflare:
  enabled: false
  tunnelId: ''
ingress:
  enabled: false
  domain: ''
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: ''
    external-dns.alpha.kubernetes.io/ttl: '120'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: '0'
service:
  type: ClusterIP
  port: 8989
serviceAccount:
  create: true
  automount: true
  annotations: {}
image:
  repository: lscr.io/linuxserver/sonarr
  pullPolicy: IfNotPresent
  tag: '4.0.14.2939-ls283'
postgres:
  enabled: false
  instances: 3
  storageClass: ''
  storage: 10Gi
apiKey: ''
profilarr:
  enabled: false
  url: ''
  apiKeySecret: ''
  apiKeySecretKey: ''
