---
apiVersion: v2
name: overseerr
description: Overseerr is a request management and media discovery tool for the Plex
  ecosystem
type: application
version: 0.2.1
appVersion: 1.33.2
dependencies:
  - name: common
    version: 0.1.7
    repository: file://../common
maintainers:
  - name: thoreinstein
    email: thore@thoreinstein.com
