apiVersion: v2
name: overseerr
description: A Helm chart for Kubernetes
type: application
version: 0.2.4
appVersion: "1.16.0"
dependencies:
  - name: common
    version: 0.1.10
    repository: file://../common
