---
replicaCount: 1
image:
  repository: lscr.io/linuxserver/overseerr
  pullPolicy: IfNotPresent
  tag: latest
puid: '1000'
pgid: '1000'
timezone: America/New_York
service:
  type: LoadBalancer
  port: 80
ingress:
  enabled: false
  className: nginx
  tls: true
  domain: ''
  annotations: {}
nfsServer: 0.0.0.0
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi
