---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: bootstrap
  source:
    path: kustom/argocd
    repoURL: https://github.com/thoreinstein/charts
    targetRevision: HEAD
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
