---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: media-stack
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          # - appName: sonarr
          #   registry: ghcr.io/linuxserver
          # - appName: radarr
          #   registry: ghcr.io/linuxserver
          # - appName: overseerr
          #   registry: ghcr.io/linuxserver
          # - appName: fileflows
          #   registry: revenz
          # - appName: tautulli
          #   registry: ghcr.io/linuxserver
          # - appName: notifiarr
          #   registry: golift
          - appName: bazarr
            registry: lscr.io/linuxserver/bazarr
          # - appName: tubesync
          #   registry: ghcr.io/meeb
  template:
    metadata:
      name: '{{.appName}}'
      annotations:
        argocd-image-updater.argoproj.io/image-list: '{{.appName}}={{.registry}}/{{.appName}}:latest'
        argocd-image-updater.argoproj.io/{{.appName}}.update-strategy: digest
        argocd-image-updater.argoproj.io/write-back-method: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/thoreinstein/manifests.git
        targetRevision: HEAD
        path: media/{{.appName}}
      destination:
        name: in-cluster
        namespace: media
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions: [CreateNamespace=true]
