---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: media-stack
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - appName: plex
            version: 0.1.*
            url: https://thoreinstein.github.io/charts
          - appName: plex-media-server
            version: 0.9.*
            url: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
          - appName: sonarr
            version: 0.3.*
            url: https://thoreinstein.github.io/charts
          - appName: radarr
            version: 0.4.*
            url: https://thoreinstein.github.io/charts
          - appName: profilarr
            version: 0.1.*
            url: https://thoreinstein.github.io/charts
          - appName: tautulli
            version: 0.1.*
            url: https://thoreinstein.github.io/charts
          - appName: overseerr
            version: 0.1.*
            url: https://thoreinstein.github.io/charts
  template:
    metadata:
      name: '{{.appName}}'
    spec:
      project: default
      sources:
        - repoURL: '{{.url}}'
          targetRevision: '{{.version}}'
          chart: '{{.appName}}'
          helm:
            valueFiles: [$values/common.yaml, '$values/{{.appName}}.yaml']
            ignoreMissingValueFiles: true
        - repoURL: git@github.com/thoreinstein/values.git
          targetRevision: HEAD
          ref: values
      destination:
        name: in-cluster
        namespace: media
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
        managedNamespaceMetadata:
          labels:
            pod-security.kubernetes.io/enforce: privileged
            pod-security.kubernetes.io/audit: privileged
            pod-security.kubernetes.io/warn: privileged
