---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: media-stack
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - appName: sonarr
            registry: lscr.io/linuxserver/sonarr
            version: 0.1.*
            url: https://thoreinstein.github.io/charts
          # - appName: radarr
          #   registry: lscr.io/linuxserver/radarr
          #   version: 0.1.6
          #   url: https://thoreinstein.github.io/charts
  template:
    metadata:
      name: '{{.appName}}'
      annotations:
        argocd-image-updater.argoproj.io/image-list: '{{.appName}}={{.registry}}/{{.appName}}:latest'
        argocd-image-updater.argoproj.io/{{.appName}}.update-strategy: digest
        argocd-image-updater.argoproj.io/write-back-method: argocd
    spec:
      project: default
      sources:
        - repoURL: '{{.url}}'
          targetRevision: '{{.version}}'
          chart: '{{.appName}}'
          helm:
            valueFiles: [$values/common.yaml, '$values/{{.appName}}.yaml']
            ignoreMissingValueFiles: true
        - repoURL: git@github.com/thoreinstein/values.git
          targetRevision: HEAD
          ref: values
      destination:
        name: in-cluster
        namespace: media
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions: [CreateNamespace=true]
