---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: media-stack
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - appName: bazarr
            registry: lscr.io/linuxserver/bazarr
  template:
    metadata:
      name: '{{.appName}}'
      annotations:
        argocd-image-updater.argoproj.io/image-list: '{{.appName}}={{.registry}}/{{.appName}}:latest'
        argocd-image-updater.argoproj.io/{{.appName}}.update-strategy: digest
        argocd-image-updater.argoproj.io/write-back-method: argocd
    spec:
      project: default
      sources:
        - repoURL: https://github.com/thoreinstein/manifests.git
          targetRevision: HEAD
          path: media/{{.appName}}
          helm:
            valueFiles: [$values/{{.appName}}.yaml]
            ignoreMissingValueFiles: false
        - repoURL: git@github.com/thoreinstein/values.git
          targetRevision: HEAD
          ref: values
      destination:
        name: in-cluster
        namespace: media
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions: [CreateNamespace=true]
