---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          # - appName: kube-prometheus-stack
          #   version: 70.4.*
          #   url: https://prometheus-community.github.io/helm-charts
          #   namespace: monitoring
          #   wave: 1
          # - appName: loki
          #   version: 6.29.*
          #   url: https://grafana.github.io/helm-charts
          #   namespace: monitoring
          #   wave: 2
          # - appName: tenant
          #   version: 7.0.*
          #   url: https://operator.min.io
          #   namespace: monitoring
          #   wave: 0
  template:
    metadata:
      name: '{{.appName}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{.wave}}'
    spec:
      project: default
      sources:
        - repoURL: '{{.url}}'
          targetRevision: '{{.version}}'
          chart: '{{.appName}}'
          helm:
            valueFiles: ['$values/{{.appName}}.yaml']
            ignoreMissingValueFiles: true
        - repoURL: git@github.com:thoreinstein/values.git
          targetRevision: HEAD
          ref: values
      destination:
        name: in-cluster
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
        managedNamespaceMetadata:
          labels:
            pod-security.kubernetes.io/enforce: privileged
            pod-security.kubernetes.io/audit: privileged
            pod-security.kubernetes.io/warn: privileged

