---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: setup
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - appName: ingress-nginx
            version: 4.12.*
            url: https://kubernetes.github.io/ingress-nginx
            namespace: networking
          - appName: cloudnative-pg
            version: 0.23.*
            url: https://cloudnative-pg.github.io/charts
            namespace: core
          - appName: metrics-server
            version: 3.12.*
            url: https://kubernetes-sigs.github.io/metrics-server/
            namespace: kube-system
          - appName: issuers
            version: 0.1.*
            url: https://thoreinstein.github.io/charts
            namespace: cert-manager
  template:
    metadata:
      name: '{{.appName}}'
    spec:
      project: default
      sources:
        - repoURL: '{{.url}}'
          targetRevision: '{{.version}}'
          chart: '{{.appName}}'
          helm:
            valueFiles: ['$values/{{.appName}}.yaml']
            ignoreMissingValueFiles: true
        - repoURL: git@github.com:thoreinstein/values.git
          targetRevision: HEAD
          ref: values
      destination:
        name: in-cluster
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
        managedNamespaceMetadata:
          labels:
            pod-security.kubernetes.io/enforce: privileged
            pod-security.kubernetes.io/audit: privileged
            pod-security.kubernetes.io/warn: privileged
