---
apiVersion: v1
kind: Pod
metadata:
  name: utils
spec:
  containers:
    - name: alpine
      image: alpine
      command: [sleep, infinity]
      securityContext:
        capabilities:
          add: [NET_ADMIN]
      stdin: true
      tty: true
  restartPolicy: Never
