{{- include "common.nfs-volume.tpl" (dict
 "name" (printf "%s-configs" (include "radarr.name" .))
 "server" (required "You must provide an NFS server address." .Values.nfsServer)
 "path" (printf "/mnt/user/kube/%s" (include "radarr.name" . ))
)}}
