{{/* {{- include "common.config-volume.tpl" (dict */}}
{{/*  "name" (include "sonarr.name" (dict "Chart" .Chart "Values" .Values)) */}}
{{/*  "server" (required "You must provide an NFS server address." .Values.nfsServer) */}}
{{/*  "path" (printf "/mnt/user/kube/%s" (include "sonarr.name" (dict "Chart" .Chart "Values" .Values))) */}}
{{/* )}} */}}
