---
ingress:
  enabled: false
  domain: ''
  className: nginx
  tls: true
  annotations: {}
service:
  type: LoadBalancer
  port: 80
serviceAccount:
  create: true
  automount: true
  annotations: {}
replicaCount: 1
image:
  repository: lscr.io/linuxserver/tautulli
  pullPolicy: IfNotPresent
  tag: latest
nfsServer: 0.0.0.0
puid: '1000'
pgid: '1000'
timezone: America/New_York
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
