{{- if .Values.awx.adminPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "awx.fullname" . }}-admin-password
  labels:
    {{- include "awx.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.awx.adminPassword }}
{{- end }}