{{- if and .Values.awx.database.external (not .Values.awx.database.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "awx.fullname" . }}-postgres-configuration
  labels:
    {{- include "awx.labels" . | nindent 4 }}
type: Opaque
stringData:
  host: {{ .Values.awx.database.host }}
  port: {{ .Values.awx.database.port | quote }}
  database: {{ .Values.awx.database.name }}
  username: {{ .Values.awx.database.username }}
  {{- if .Values.awx.database.password }}
  password: {{ .Values.awx.database.password }}
  {{- end }}
  type: unmanaged
{{- end }}

{{- if and .Values.awx.database.external .Values.awx.database.existingSecretName }}
# Use existing secret for database configuration
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "awx.fullname" . }}-postgres-configuration
  labels:
    {{- include "awx.labels" . | nindent 4 }}
type: Opaque
stringData:
  type: unmanaged
{{- end }}