---
apiVersion: v2
name: mealie
description: A self-hosted recipe management and meal planning application
type: application
version: 0.1.1
appVersion: v1.3.2
maintainers:
  - name: thoreinstein
dependencies:
  - name: common
    version: '*'
    repository: file://../common
