replicaCount: 1
nfsServer: ''
image:
  repository: ghcr.io/mealie-recipes/mealie
  pullPolicy: IfNotPresent
  tag: v2.8.0
serviceAccount:
  create: true
  annotations: {}
  name: ''
service:
  type: ClusterIP
  port: 80
  annotations: {}
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/proxy-body-size: '0'
  domain: ""
  tls: false
cloudflare:
  enabled: false
env:
  PUID: 1000
  PGID: 1000
  allowSignup: 'false'
hostAliases: []
oidc:
  enabled: false
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi
timezone: America/New_York
postgres:
  storageClass: longhorn
