---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: postgres
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: {{ .Values.postgres.numberOfReplicas | quote }}
  staleReplicaTimeout: "2880"
  dataLocality: "strict-local"
  fromBackup: ""
  recurringJobSelector: '[
    {
      "name":"postgres-snap",
      "isGroup":true
    },
    {
      "name":"postgres-backup",
      "isGroup":true
    }
  ]'
