---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: postgres-backup
  namespace: longhorn-system
spec:
  cron: {{ .Values.postgres.backupCron | quote }}
  task: backup
  groups:
  - postgres-backup
  retain: {{ .Values.postgres.backupRetain }}
  concurrency: 1
  labels:
    recurring-job-type: postgres
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: postgres-snapshot
  namespace: longhorn-system
spec:
  cron: {{ .Values.postgres.snapshotCron | quote }}
  task: snapshot
  groups:
  - postgres-snap
  retain: {{ .Values.postgres.snapshotRetain }}
  concurrency: 1
  labels:
    recurring-job-type: postgres
