---
apiVersion: v2
name: cert-manager
description: Cert Manager
maintainers:
  - name: Thor
type: application
version: 0.1.2
appVersion: v1.17.1
dependencies:
  - name: cert-manager
    version: v1.17.1
    repository: https://charts.jetstack.io
