apiVersion: v2
name: karakeep
description: Bookmark Everything with AI-powered tagging and search
type: application
version: 0.2.0
appVersion: latest
icon: https://raw.githubusercontent.com/karakeep-app/karakeep/main/public/logo.png
maintainers:
  - name: thoreinstein
dependencies:
  - name: common
    version: '0.1.12' # Updated version
    repository: file://../common
