{{- include "common.nfs-volume.tpl" (dict
  "name" (printf "%s-config" (include "tautulli.name" .))
 "server" (required "You must provide an NFS server address." .Values.nfsServer)
 "path" (printf "/mnt/user/appdata/%s" (include "tautulli.name" .))
)}}
