{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tautulli.fullname" . }}
  labels:
    {{- include "tautulli.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
spec:
  tls:
    - hosts:
        - {{ include "tautulli.domain_name" . }}
      secretName: {{ include "tautulli.name" . }}-tls
  rules:
    - host: {{ include "tautulli.domain_name" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "tautulli.fullname" . }}
                port:
                  name: http
{{- end }}