---
apiVersion: v2
name: plex
description: A Helm chart for Plex Media Server
type: application
version: 0.1.0
appVersion: latest
maintainers:
  - name: thoreinstein
dependencies:
  - name: common
    version: '*'
    repository: file://../common

