---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.myersha.us
  statusbadge.enabled: 'false'
  users.anonymous.enabled: 'false'
  resource.exclusions: |-
    - apiGroups:
      - cilium.io
      kinds:
      - CiliumIdentity
      clusters:
      - "*"
