{{- $domain_name := include "common.domain_name"  (dict
  "domain" .Values.ingress.domain
  "name" "argocd"
)}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "acme-staging"
spec:
  rules:
  - host: {{ $domain_name }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
               number: 80
