---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-channels-dvr-config
  labels:
    {{- include "channels-dvr.labels" . | nindent 4 }}
provisioner: nfs.csi.k8s.io
parameters:
  server: {{ .Values.nfsServer | quote }}
  share: /mnt/tank/k8s/channels-dvr/config
  mountPermissions: "0755"
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-channels-dvr-recordings
  labels:
    {{- include "channels-dvr.labels" . | nindent 4 }}
provisioner: nfs.csi.k8s.io
parameters:
  server: {{ .Values.nfsServer | quote }}
  share: /mnt/tank/k8s/channels-dvr/recordings
  mountPermissions: "0755"
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate