---
apiVersion: v2
name: paperless-ngx
description: A Helm chart for Paperless-ngx document management system
type: application
version: 0.1.1
appVersion: 2.2.1
maintainers:
  - name: thoreinstein
dependencies:
  - name: common
    version: '*'
    repository: file://../common
  - name: redis
    version: 20.13.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
