{{- range required "IP Pools must be provided!" .Values.ipPools }}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .name }}
spec:
  addresses:
    - {{ .range }}
  avoidBuggyIPs: true
{{- end }}
