{{- range required "IP Pools must be provided!" .Values.ipPools }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .name }}
spec:
  ipAddressPools:
    - {{ .name }}
{{- end }}
