apiVersion: v1
kind: Service
metadata:
  name: {{ include "huntarr.fullname" . }}
  labels:
    {{- include "huntarr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      number: 80
  selector:
    {{- include "huntarr.selectorLabels" . | nindent 4 }}
