---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sonarr.fullname" . }}-api-key
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.apiKey | default (randAlphaNum 32) | b64enc | quote }}
