---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sonarr.fullname" . }}
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  # This is a template that will be processed by the init container
  config.xml.template: |-
    <Config>
      <BindAddress>*</BindAddress>
      <Port>8989</Port>
      <SslPort>9898</SslPort>
      <EnableSsl>False</EnableSsl>
      <LaunchBrowser>True</LaunchBrowser>
      <ApiKey>${API_KEY}</ApiKey>
      <AuthenticationMethod>Forms</AuthenticationMethod>
      <AuthenticationRequired>DisabledForLocalAddresses</AuthenticationRequired>
      <Branch>main</Branch>
      <LogLevel>debug</LogLevel>
      <SslCertPath></SslCertPath>
      <SslCertPassword></SslCertPassword>
      <UrlBase></UrlBase>
      <InstanceName>Sonarr</InstanceName>
      <UpdateMechanism>Docker</UpdateMechanism>
      <PostgresHost>${POSTGRES_HOST}</PostgresHost>
      <PostgresPort>${POSTGRES_PORT}</PostgresPort>
      <PostgresUser>${POSTGRES_USER}</PostgresUser>
      <PostgresPassword>${POSTGRES_PASSWORD}</PostgresPassword>
      <AnalyticsEnabled>False</AnalyticsEnabled>
    </Config>