{{- $domain_name := include "common.domain_name"  (dict
  "domain" .Values.ingress.domain
  "name" (include "sonarr.name" .)
)}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sonarr.fullname" . }}
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "acme-staging"
spec:
  rules:
  - host: {{ $domain_name }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "sonarr.fullname" . }}
            port:
              number: {{ .Values.service.port }}
