{{- if .Values.ingress.enabled }}
{{- $domain_name := include "common.domain_name"  (dict
  "domain" .Values.ingress.domain
  "name" (include "sonarr.name" .)
)}}
{{- $fullname := include "sonarr.fullname" . }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.security.enableSecurityHeaders }}
    # Security headers
    nginx.ingress.kubernetes.io/x-frame-options: "SAMEORIGIN"
    nginx.ingress.kubernetes.io/x-content-type-options: "nosniff"
    nginx.ingress.kubernetes.io/x-xss-protection: "1; mode=block"
    nginx.ingress.kubernetes.io/referrer-policy: "strict-origin-when-cross-origin"
    {{- end }}
    {{- if .Values.ingress.performance.enableOptimizations }}
    # Performance optimizations
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/ssl-session-timeout: "10m"
    nginx.ingress.kubernetes.io/ssl-session-cache-size: "10m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "{{ .Values.ingress.performance.timeouts.connect }}"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "{{ .Values.ingress.performance.timeouts.send }}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{ .Values.ingress.performance.timeouts.read }}"
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.domain }}
  tls:
  - hosts:
    - {{ $domain_name }}
    secretName: {{ $fullname }}-tls
  {{- end }}
  rules:
  - host: {{ $domain_name }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $fullname }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
