{{- if .Values.ingress.enabled }}
{{- $domain_name := include "common.domain_name"  (dict
  "domain" .Values.ingress.domain
  "name" (include "sonarr.name" .)
)}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sonarr.name" . }}
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ $domain_name }}
    secretName: {{ include "sonarr.name" . }}-tls
  {{- end }}
  rules:
  - host: {{ $domain_name }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "sonarr.name" . }}
            port:
              number: 80
{{- end }}
