{{- include "common.nfs-volume.tpl" (dict
 "name" (printf "%s-media" (include "sonarr.name" .))
 "server" (required "You must provide an NFS server address." .Values.media.nfsServer)
 "path" .Values.media.nfsPath
)}}
