---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "sonarr.fullname" . }}-postgres
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  instances: 3
  
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "1GB"
      maintenance_work_mem: "64MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "4MB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"

  bootstrap:
    initdb:
      database: sonarr-main
      owner: sonarr
      postInitSQL:
        - CREATE DATABASE "sonarr-log" OWNER sonarr;

  storage:
    size: 10Gi
    storageClass: {{ .Values.postgres.storageClass | default "longhorn" }}

  monitoring:
    enabled: true