---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sonarr.fullname" . }}-db-credentials
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: sonarr
  password: {{ randAlphaNum 16 | quote }}
  sonarr-user: sonarr
  sonarr-password: {{ randAlphaNum 16 | quote }}