---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sonarr.fullname" . }}
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "sonarr.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "sonarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sonarr.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "sonarr.serviceAccountName" . }}
      initContainers:
        - name: wait-for-postgres
          image: postgres:15-alpine
          command:
            - "/bin/sh"
            - "-c"
            - |
              echo "Waiting for PostgreSQL to be ready..."
              until pg_isready -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER; do
                echo "PostgreSQL is not ready yet..."
                sleep 2
              done
              echo "PostgreSQL is ready!"
          env:
            - name: POSTGRES_HOST
              value: {{ include "sonarr.fullname" . }}-postgres-rw
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "sonarr.fullname" . }}-postgres-app
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "sonarr.fullname" . }}-postgres-app
                  key: password
        - name: volume-permissions
          image: busybox:1.36.1
          command: ["/bin/sh", "-c"]
          args:
            - |
              chown -R 99:100 /config && chmod -R 755 /config
          volumeMounts:
            - name: config
              mountPath: /config
        - name: {{ .Chart.Name }}-init
          image: busybox:1.36.1
          command:
            - "/bin/sh"
            - "-c"
            - |
              if [ ! -f /config/config.xml ]; then
                echo "Creating initial config.xml..."
                cat /tmp/config/config.xml.template | \
                sed "s/\${POSTGRES_HOST}/$POSTGRES_HOST/g" | \
                sed "s/\${POSTGRES_PORT}/$POSTGRES_PORT/g" | \
                sed "s/\${POSTGRES_USER}/$POSTGRES_USER/g" | \
                sed "s/\${POSTGRES_PASSWORD}/$POSTGRES_PASSWORD/g" | \
                sed "s/\${API_KEY}/$API_KEY/g" > /config/config.xml && \
                chmod 644 /config/config.xml
              else
                echo "Config file already exists, preserving existing configuration"
              fi
          env:
            - name: POSTGRES_HOST
              value: {{ include "sonarr.fullname" . }}-postgres-rw
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "sonarr.fullname" . }}-postgres-app
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "sonarr.fullname" . }}-postgres-app
                  key: password
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "sonarr.fullname" . }}-api-key
                  key: api-key
          volumeMounts:
            - name: config-init
              mountPath: /tmp/config
            - name: config
              mountPath: /config
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PUID
              value: "99"
            - name: PGID
              value: "100"
            - name: UMASK
              value: "022"
            - name: TZ
              value: America/New_York
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: media
              mountPath: /media
            - name: config
              mountPath: /config
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: {{ include "sonarr.name" . }}-media-pvc
        - name: config-init
          configMap:
            name: {{ include "sonarr.fullname" . }}
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 1Gi
