{{- if .Values.paperlessGpt.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-gpt
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: paperless-gpt
spec:
  type: {{ .Values.paperlessGpt.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.paperlessGpt.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "paperless-ngx.gptSelectorLabels" . | nindent 4 }}
{{- end }}
