---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: paperless
  namespace: paperless
spec:
  encryptedData:
    password: AgBpdoVY6r3shu/bu274G4f/mesWmrJU22Fwyv1C+T1EuFKUWA6aDA+FuhlxvKGpsoSEntGY17hunkvVHILjAcvrYxR5Xs4qPisScNj+3g2MCJ3HhDXzbSrkUr52Jnn3LUw//kqBW5pn7HqsjmMcYzei+oaEI/YNrkCKQ9yIXs1ohYnFwrnvd1pYR04UubwKOY2hmDpLIoO+V5nCgyU6Qogzvy1reuEKvzGrZSIx99YvALUsj1aEjTW1V/w/Vd/guaXAavyBUrpxTs941J2yogw3uR+DkhFXtTLbL3DzMxCIGZtfJmQiTAXPHkqMy09F/W1MuZWJDnHbbxKO5albOYePLgBAcibTwHdtEqM5NXxC9zSbKGf9wpOAwM2/UKE9cL29oPAV4JEK5gGwFdE8IivenFroRsXnFW4wbO/lFf712EAhtMjz3/DmghQRfGIZorWSe+sxE6DYu+yJHTqOt4zCKKNrHsAWW808Erf6vw1vkYTgupdXnnQC43OckKj0ET2W7Rrn8qbzHbV7ZASnXnZbFXJ32sxtZNuzu6PVa/SUzkiPOFNxTJjfDKXoFQUr5EaSBbT2ZT99liYNw+P652sk5NqPSuKpv6/uOGUyEx5aD6e4zmcHP5ZYmoCEcnPTv7taU6ryuXBlqLCVLDyE/CjufyjUbiEVAfSti76CXkj8z4cKEBYa1C2jzFz9T5ZHCpV9dwmyepVJiXY2T0YO/DNRnQp8Uw==
    user: AgASpUHsFSIkWFbTyJOG3hO0HcPyzYNaZwTjpVwcz7v7G9kFW2r28hgK02nUSYOnM60z6ZWtn9K2Q6hblwP1tJ3GRzkHCADxcOH0TID9LV/L6HtcHMVD0yTIFQGnpMw+W7iYs830JO8Zw7c5BiaiJ5CcbdQ5zcmT2n7OrpJsNxaOa3Sl3kq6hO6r7Ol4TIAvB6OAIFXqAaIJK81K3au4324frw08sUTosGB/pXkz1HkSaMJ9w61aTcoceCGsgpsxBp8dylGd5fZBEDiCa+HfcbuQ0Qrja96VA2VwtUkokdpktSGhl1C7s+GWyoQDOu9wzhfR8iiBGYPjTY3F1U5aprrKu2I9SH8F65steOKfHYSP/9u9jgRtC98iz0XV36GkISWoWx70eqhFf1QRhFgt+G+zQcsf9r4A+2O0AFHyLKmGxccl67++HQ/fThj4/atoieogeMrE4UaObnI4fVJdzN9tNhma16DOZaTRHfqe7/UkVihtAOw0gQCHBxL8Fu1ZS6+4UdBBKVvY98s6lqJo5mCPEY86N0f3bB71ZNvRACzb/QiqXsArSEZD5KArSB218ra+SICMRGhHLUbFB6X9ZF8byLfn/yk/9MeX/RCwp7L9CcxvooQd+cm4WVzbbsN92fmGVMtw+wV3oAJIN6zOw0hn4S5ygeq5YqxQqlg+JaHooupZmIy0bE0vbgfCU5520wjSBD1Rtw==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: paperless-ngx
      name: paperless
      namespace: paperless
    type: Opaque
