{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "paperless-ngx.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
{{- end }}
