apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "paperless-ngx.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "paperless-ngx.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "paperless-ngx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "paperless-ngx.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "paperless-ngx.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PAPERLESS_REDIS
              value: redis://{{ .Release.Name }}-redis-master:6379
            - name: PAPERLESS_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: paperless
                  key: user
            - name: PAPERLESS_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paperless
                  key: password
            - name: PAPERLESS_DBHOST
              valueFrom:
                secretKeyRef:
                  name: paperless-db-credentials
                  key: host
            - name: PAPERLESS_DBPORT
              valueFrom:
                secretKeyRef:
                  name: paperless-db-credentials
                  key: port
            - name: PAPERLESS_DBUSER
              valueFrom:
                secretKeyRef:
                  name: paperless-db-credentials
                  key: username
            - name: PAPERLESS_DBPASS
              valueFrom:
                secretKeyRef:
                  name: paperless-db-credentials
                  key: password
            - name: PAPERLESS_CONSUMER_POLLING
              value: {{ .Values.pollingInterval | default 300 | quote }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /usr/src/paperless/data
            - name: media
              mountPath: /usr/src/paperless/media
            - name: consume
              mountPath: /usr/src/paperless/consume
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "paperless-ngx.fullname" . }}-data-pvc
        - name: media
          persistentVolumeClaim:
            claimName: {{ include "paperless-ngx.fullname" . }}-media-pvc
        - name: consume
          persistentVolumeClaim:
            claimName: {{ include "paperless-ngx.fullname" . }}-consume-pvc
