---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "profilarr.fullname" . }}
  labels:
    {{- include "profilarr.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "profilarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "profilarr.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "profilarr.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TZ
              value: {{ .Values.timezone | quote }}
          ports:
            - name: http
              containerPort: 6868
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "profilarr.name" . }}-config-pvc
