{{- if .Values.apiKey.autoCreate }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "profilarr.fullname" . }}-secret-creator
  labels:
    {{- include "profilarr.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "patch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "profilarr.fullname" . }}-secret-creator
  labels:
    {{- include "profilarr.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "profilarr.fullname" . }}-secret-creator
subjects:
  - kind: ServiceAccount
    name: {{ include "profilarr.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}