apiVersion: v1
kind: Secret
metadata:
  name: {{ include "overseerr.fullname" . }}-api-key
  labels:
    {{- include "overseerr.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.apiKey | b64enc | quote }}