{{- include "common.nfs-volume.tpl" (dict
  "name" (printf "%s-data" (include "overseerr.name" .))
  "server" (required "You must provide an NFS server address." .Values.nfsServer)
  "path" (printf "/mnt/user/appdata/%s" (include "overseerr.name" .))
)}}
