apiVersion: v1
kind: Service
metadata:
  name: {{ include "karakeep.fullname" . }}-chrome
  labels:
    {{- include "karakeep.labels" . | nindent 4 }}
    app.kubernetes.io/component: chrome
spec:
  type: ClusterIP
  ports:
    - port: 9222
      targetPort: devtools
      protocol: TCP
      name: devtools
  selector:
    {{- include "karakeep.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: chrome