apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "karakeep.fullname" . }}-chrome
  labels:
    {{- include "karakeep.labels" . | nindent 4 }}
    app.kubernetes.io/component: chrome
spec:
  replicas: {{ .Values.chrome.replicaCount }}
  selector:
    matchLabels:
      {{- include "karakeep.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: chrome
  template:
    metadata:
      labels:
        {{- include "karakeep.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: chrome
    spec:
      serviceAccountName: {{ include "karakeep.serviceAccountName" . }}
      containers:
        - name: chrome
          image: "{{ .Values.chromeImage.repository }}:{{ .Values.chromeImage.tag }}"
          imagePullPolicy: {{ .Values.chromeImage.pullPolicy }}
          {{- with .Values.chrome.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              exec chromium-browser \
                --headless \
                --no-sandbox \
                --disable-gpu \
                --disable-dev-shm-usage \
                --remote-debugging-address=0.0.0.0 \
                --remote-debugging-port=9222 \
                --hide-scrollbars \
                about:blank
          ports:
            - name: devtools
              containerPort: 9222
              protocol: TCP
          resources:
            {{- toYaml .Values.chromeResources | nindent 12 }}
