{{- include "common.smb-volume.tpl" (dict
  "name" (printf "%s-data" .Chart.Name)
  "server" (required "You must provide a storage server address." (default .Values.nfsServer .Values.storage.server))
  "share" (printf "appdata/%s" .Chart.Name)
)}}
---
{{- include "common.smb-volume.tpl" (dict
  "name" (printf "%s-meili-data" .Chart.Name)
  "server" (required "You must provide a storage server address." (default .Values.nfsServer .Values.storage.server))
  "share" (printf "appdata/%s-meili" .Chart.Name)
)}}
