apiVersion: v1
kind: Service
metadata:
  name: {{ include "karakeep.fullname" . }}-meilisearch
  labels:
    {{- include "karakeep.labels" . | nindent 4 }}
    app.kubernetes.io/component: meilisearch
spec:
  type: ClusterIP
  ports:
    - port: 7700
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "karakeep.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: meilisearch