---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: karakeep
  namespace: karakeep
spec:
  encryptedData:
    auth-secret: AgBFiibPdi6VulnjuWaX1oJ60aS1RTpTyVb1TDbPOyYHHpjceQmua5XvWVzw0rXM6MOaFeD+7t73UL7UWzCpxoeYzVOTcyWs7kRMjCfnkKK5wHEM1aznLdRd+ZsvNUuSTD3xCzE1RTvjthWYd8Jn8oEvPZNjPkxWs7wm+XY+h9EpbhK4o3n7w2+V0XbGFFatqJAIxnu/VVud+KPKNwHibp5CVhhFOWdxVr9l6ECi/b3h9dQKDPxsvE05JKIs1LisuerKBWrHyZdHnCMLTedSenBhmpvf1b11tyDB1uNbDBb3a1WHt+PSrmU1wAGnXIQqfDKPR46BUyGo3H3KjvepjZ1G14WY7Kf4WIufKRpOQ8xJs7Cna+vj4K3+q6us43BwOCgThY2jZf74eido3szGCF69MdvpbtrTrNKax5PcmtCAJPoHZjvTOLBVZ7QuYNIhxdgrGE2O5czEJG+mIWrYgzs0GXonB3SOGxVa32VQ68p2buy+5x1wxr/qw+EJpQ7uw9syUDYy/cA/2FkpDDOUp1Ah0AZqIBCUEaSIeV4r83kWYmBDstKn2KX1tgjVpGcbDC/AJA0K8hUt0S2dj4X5cSIQ0NZ5hU8VwBPF5mSqTyEq3F4GKXQ3FtZ7pyAkGzxzEiv2ccNBLfET1brzW/SNXoKuIm9M9Crt2TAPml2ReO8N0CWng+stUSOSFYcPu/8ulnBNVTSRDn4qQiAK8IVgbsxkWsu/NLauaxPVth9e8KKd8aUHzqM9+ONcHy3zI2PgG3o=
    meili-master-key: AgBFiibPdi6VulnjuWaX1oJ60aS1RTpTyVb1TDbPOyYHHpjceQmua5XvWVzw0rXM6MOaFeD+7t73UL7UWzCpxoeYzVOTcyWs7kRMjCfnkKK5wHEM1aznLdRd+ZsvNUuSTD3xCzE1RTvjthWYd8Jn8oEvPZNjPkxWs7wm+XY+h9EpbhK4o3n7w2+V0XbGFFatqJAIxnu/VVud+KPKNwHibp5CVhhFOWdxVr9l6ECi/b3h9dQKDPxsvE05JKIs1LisuerKBWrHyZdHnCMLTedSenBhmpvf1b11tyDB1uNbDBb3a1WHt+PSrmU1wAGnXIQqfDKPR46BUyGo3H3KjvepjZ1G14WY7Kf4WIufKRpOQ8xJs7Cna+vj4K3+q6us43BwOCgThY2jZf74eido3szGCF69MdvpbtrTrNKax5PcmtCAJPoHZjvTOLBVZ7QuYNIhxdgrGE2O5czEJG+mIWrYgzs0GXonB3SOGxVa32VQ68p2buy+5x1wxr/qw+EJpQ7uw9syUDYy/cA/2FkpDDOUp1Ah0AZqIBCUEaSIeV4r83kWYmBDstKn2KX1tgjVpGcbDC/AJA0K8hUt0S2dj4X5cSIQ0NZ5hU8VwBPF5mSqTyEq3F4GKXQ3FtZ7pyAkGzxzEiv2ccNBLfET1brzW/SNXoKuIm9M9Crt2TAPml2ReO8N0CWng+stUSOSFYcPu/8ulnBNVTSRDn4qQiAK8IVgbsxkWsu/NLauaxPVth9e8KKd8aUHzqM9+ONcHy3zI2PgG3o=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: karakeep
      name: karakeep
      namespace: karakeep
    type: Opaque
