---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: karakeep
  namespace: karakeep
spec:
  encryptedData:
    auth-secret: AgAKZhGQGVTp89gjNqcd2ccJUh2eh8sTA7XIHGOoPo5hogBvCDZD620cRPa//oY7TBRGRtkbBMfFCbD+5no1IhAKE8NCogQ/l8yMeZzJsqJoiTZ2KDP1rlaQDPU0Br6X7fLWgjCiZkAEhFKKIxXrRnHVejTGA4yBoa7nmkeQaAJ/QKy/WATYMhmjqTb3vcw1tzyrALbtRaFt+9JB97zXEYn3UltPoSc1kFZ9OaheLZzpDlCiL1L4j2L9yH4RoOmAeBTWYWRAt6PTKl7lCgST2wUYrYXtatLsKMSACawPP7I8trZ5/uv69zgxuEm8OaXuo6RBi65LTEKf1XbV3GPYCUXM5Wh1WzEjzSiRBWajrVFuWaw4NKt6uOQ6kQAcQbEs/nHrVjrI3gk4REJ0zLas3b90DrjOJ1SLk+9NK07GNd/iFDbzf+mb4AW93qiPaXrAxku+edTCp5Rw1jFSnZ5sDT1b0DAa06CXikBW0cJnVYPnMRGLLWQ+M+H2dUBsk+q17v3c4zOoeI9dLH8vTj4TDJl16LL29SIYTT7clfWQRdue4Im6XeIheBTZtLOOmZhlcC0li/zVbF/j2fRyM0cSdv1xALBY8KI6OuccF6ggdpf6H1yX6DUWV6Si9L6VbPC4kHKVrG+8u8dDnh5wUgQKP3lNhaff4/gJV6r3YXVX0vYLtqIMFTrPA2soxrX+fn0HzLN5v7QVFmBfTx0eFzd5zQ4nGJxhbb6wMFAm1WZJ7FsWfGdaDSsjc/t75qvFPfmGAzo=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: karakeep
      name: karakeep
      namespace: karakeep
    type: Opaque
