{{/* --- */}}
{{/* apiVersion: v1 */}}
{{/* kind: PersistentVolume */}}
{{/* metadata: */}}
{{/*   name: bazarr-config-pv */}}
{{/* spec: */}}
{{/*   capacity: */}}
{{/*     storage: 2Gi */}}
{{/*   accessModes: [ReadWriteOnce] */}}
{{/*   nfs: */}}
{{/*     server: 10.10.0.20 */}}
{{/*     path: /mnt/user/kube/bazarr */}}
{{/*   persistentVolumeReclaimPolicy: Retain */}}
{{/* --- */}}
{{/* apiVersion: v1 */}}
{{/* kind: PersistentVolumeClaim */}}
{{/* metadata: */}}
{{/*   name: bazarr-config-pvc */}}
{{/*   labels: */}}
{{/*     app: bazarr */}}
{{/* spec: */}}
{{/*   accessModes: [ReadWriteOnce] */}}
{{/*   volumeName: bazarr-config-pv */}}
{{/*   storageClassName: '' */}}
{{/*   resources: */}}
{{/*     requests: */}}
{{/*       storage: 2Gi */}}
