apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bazarr.fullname" . }}
  labels:
    {{- include "bazarr.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bazarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bazarr.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "bazarr.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PUID
              value: "99"
            - name: PGID
              value: "100"
            - name: UMASK
              value: "022"
            - name: TZ
              value: America/New_York
            - name: POSTGRES_ENABLED
              value: "True"
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: "{{ include "bazarr.name" . }}-database-env"
                  key: HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: "{{ include "bazarr.name" . }}-database-env"
                  key: PORT
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: "{{ include "bazarr.name" . }}-database-env"
                  key: DATABASE
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "{{ include "bazarr.name" . }}-database-env"
                  key: USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ include "bazarr.name" . }}-database-env"
                  key: PASSWORD
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
