---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs-pv
spec:
  capacity:
    storage: 50Gi
  accessModes: [ReadWriteMany]
  nfs:
    server: 10.10.0.20
    path: /mnt/user/data
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs-pvc
spec:
  accessModes: [ReadWriteMany]
  volumeName: media-nfs-pv
  storageClassName: ''
  resources:
    requests:
      storage: 50Gi
