---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "bazarr.name" . }}-media-pv
spec:
  capacity:
    storage: 50Gi
  accessModes: [ReadWriteMany]
  nfs:
    server: 10.10.0.20
    path: /mnt/user/data
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bazarr.name" . }}-media-pvc
spec:
  accessModes: [ReadWriteMany]
  volumeName: {{ include "bazarr.name" . }}-media-pv
  storageClassName: ''
  resources:
    requests:
      storage: 50Gi
