---
apiVersion: v2
name: radarr
description: A Helm chart for Kubernetes
maintainers:
  - name: Thor
type: application
version: 0.1.2
appVersion: 1.16.0
dependencies:
  - name: common
    version: 0.1.4
    repository: file://../common
