---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "bazarr.name" . }}-config-pv
spec:
  capacity:
    storage: 2Gi
  accessModes: [ReadWriteOnce]
  nfs:
    server: 10.10.0.20
    path: /mnt/user/kube/{{ include "bazarr.name" . }}
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bazarr.name" . }}-config-pvc
  labels:
    app: {{ include "bazarr.name" . }}
spec:
  accessModes: [ReadWriteOnce]
  volumeName: {{ include "bazarr.name" . }}-config-pv
  storageClassName: ''
  resources:
    requests:
      storage: 2Gi
