---
name: Release Charts
on:
  push:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v4
      - name: Add dependency chart repos
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo add metallb https://metallb.github.io/metallb
          helm repo add openebs https://openebs.github.io/charts
          helm repo add cloudflare https://cloudflare.github.io/helm-charts
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
