---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: argo-cd-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: noreply@myersha.us
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      # An empty 'selector' means that this solver matches all domains
      - selector: {}
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
