---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-cd-cert
spec:
  secretName: argocd-secret-tls
  issuerRef:
    name: acme-prod
    kind: Issuer
  commonName: argocd.myersha.us
  dnsNames: [argocd.myersha.us]
