{{- range required "IP Pools must be provided!" .Values.ip_pools }}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  addresses:
    - {{ .range }}
  avoidBuggyIPs: true
{{- end }}
