{{- range required "IP Pools must be provided!" .Values.ip_pools }}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .name }}
  namespace: metallb-system
spec:
  addresses:
    - {{ .range }}
  avoidBuggyIPs: true
{{- end }}
