{{- range required "IP Pools must be provided!" .Values.ip_pools }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .name }}
  namespace: metallb-system
spec:
  ipAddressPools:
    - {{ .name }}
{{- end }}
